### ISSUE TITLE
Nested function

### ISSUE THREAD

**Issue by tchia04** [purcellconsult/Code-Cool-Stuff-With-Python#10]
ORIGINAL
The inner() function is called within the inner function

I think this should say 
The inner() function is called within the outer function

Since the code is 
<pre>

def outer():
    """this is outer"""
    x = 5
    print(x)
    def inner():
        """This is inner"""
        x = 10
        print(x)
    inner()
</pre>

If the code is the following, then you can say "The inner() function is called within the inner function
"
<pre>

def outer():
    """this is outer"""
    x = 5
    print(x)
    def inner():
        """This is inner"""
        x = 10
        print(x)
        inner()
    inner()
</pre>

**Comment by purcellconsult** [comment]
Good catch. Edited.
