### ISSUE TITLE
[Boolean Algebra] Change "or less" to "unless" 

### ISSUE THREAD

**Issue by tchia04** [purcellconsult/Code-Cool-Stuff-With-Python#4]
ORIGINAL
Remember, 0 maps to False, and 1 maps to True. A shortcut to remembering this is and is always False **or less** you have two True operands. Or, is always True **or less** you have two False operands.

SUGGESTION
Remember, 0 maps to False, and 1 maps to True. A shortcut to remembering this is and is always False **unless** you have two True operands. Or, is always True **unless** you have two False operands.

**Comment by purcellconsult** [comment]
Nice catch. Corrected.
