### ISSUE TITLE
Ternary Statement: Move "The following prints nice" before the code instead of after the code

### ISSUE THREAD

**Issue by tchia04** [purcellconsult/Code-Cool-Stuff-With-Python#6]
ORIGINAL
Ternary Statement
Is a special type of operator that evaluates something based on a condition being True or False. The best way to understand it is to take a look at a simple code snippet: 
mood = True
state = 'nice' if mood else 'not so nice'
print('state = {}'.format(state))
**The following prints nice because if mood evaluates to True.** 

NEW
Ternary Statement
Is a special type of operator that evaluates something based on a condition being True or False. The best way to understand it is to take a look at a simple code snippet: 
**The following prints nice because if mood evaluates to True.** 

mood = True
state = 'nice' if mood else 'not so nice'
print('state = {}'.format(state))

**Comment by purcellconsult** [comment]
Changed from: **The following prints nice because if mood evaluates to True.**

To:

**The above prints nice because if mood evaluates to True.**
